### ISSUE TITLE
GitHub repo description mistakenly says "nvim support for SpaceVim"

### ISSUE THREAD

**Issue by rafi** [wsdjeg/vim-nim#5]
Should be "nim support for SpaceVim" ;)

**Comment by wsdjeg** [comment]
Thanks, I will fix it.wsdjeg -------- 原始邮件 --------主题：[wsdjeg/vim-nim] Title mistakenly says "nvim support for SpaceVim" (#5)发件人：Rafael Bodill 收件人：wsdjeg/vim-nim 抄送：Subscribed Should be "nim support for SpaceVim" ;)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/wsdjeg/vim-nim/issues/5?email_source=notifications\u0026email_token=ADEITERGXPWDFGNVDFFDMK3P7YBVJA5CNFSM4IEDKHA2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G7RAYCQ",
"url": "https://github.com/wsdjeg/vim-nim/issues/5?email_source=notifications\u0026email_token=ADEITERGXPWDFGNVDFFDMK3P7YBVJA5CNFSM4IEDKHA2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G7RAYCQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
